name: Build and Publish
on:
  push:
    branches:
      - 'dev'

jobs:

  push_to_registry:

    name: Build and Push Peaq Docker Image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: "Free Disk Space (insightsengineering/disk-space-reclaimer)"
        run: |
          echo "Free disk space before cleanup"
